- src/Esfa.Vacancy.Register.Api/App_Start/AutoMapperConfig.cs
- src/Esfa.Vacancy.Register.Api/App_Start/CustomExceptionHandler.cs
- src/Esfa.Vacancy.Register.Api/Web.config
- src/Esfa.Vacancy.Register.Application/Esfa.Vacancy.Register.Application.csproj
- src/Esfa.Vacancy.Register.Application/Exceptions/ResourceNotFoundException.cs
- src/Esfa.Vacancy.Register.Application/Exceptions/UnauthorisedException.cs
- src/Esfa.Vacancy.Register.Application/Queries/GetVacancy/GetVacancyQueryHandler.cs
- src/Esfa.Vacancy.Register.Application/app.config
- src/Esfa.Vacancy.Register.Application/packages.config
- src/Esfa.Vacancy.Register.Domain/Esfa.Vacancy.Register.Domain.csproj
- src/Esfa.Vacancy.Register.Domain/Repositories/IVacancyRepository.cs
- src/Esfa.Vacancy.Register.Infrastructure/Esfa.Vacancy.Register.Infrastructure.csproj
- src/Esfa.Vacancy.Register.Infrastructure/Repositories/IVacancyRepository.cs
- src/Esfa.Vacancy.Register.Infrastructure/Repositories/VacancyRepository.cs
- src/Esfa.Vacancy.Register.Infrastructure/Settings/ApplicationSettingConstants.cs
- src/Esfa.Vacancy.Register.Infrastructure/packages.config
- src/Esfa.Vacancy.Register.UnitTests/Esfa.Vacancy.Register.UnitTests.csproj
- src/Esfa.Vacancy.Register.UnitTests/app.config
- Updated Mapping between API and Domain Vacancy type to transform Enums where applicable
> Added dapper for mapping SQL Response to Domain Entity

- src/Esfa.Vacancy.Register.Api/App_Start/CustomExceptionHandler.cs
- src/Esfa.Vacancy.Register.Api/Controllers/VacanciesController.cs
- src/Esfa.Vacancy.Register.Application/Queries/GetVacancy/GetVacancyQueryHandler.cs
- src/Esfa.Vacancy.Register.UnitTests/Application/Queries/GetVacancy/WhenGettingVacancy.cs
- src/Esfa.Vacancy.Register.UnitTests/Esfa.Vacancy.Register.UnitTests.csproj
- src/Esfa.Vacancy.Register.UnitTests/packages.config
- Added unit tests to cover the changes in the query handler.
> Updated Query Handler to raise ResourceNotFoundException.

- src/Esfa.Vacancy.Api.Types/Address.cs
- src/Esfa.Vacancy.Api.Types/Esfa.Vacancy.Api.Types.csproj
- src/Esfa.Vacancy.Api.Types/Vacancy.cs
- src/Esfa.Vacancy.Register.Api/App_Start/AutoMapperConfig.cs
- src/Esfa.Vacancy.Register.Domain/Entities/Address.cs
- src/Esfa.Vacancy.Register.Domain/Entities/Vacancy.cs
- src/Esfa.Vacancy.Register.Domain/Esfa.Vacancy.Register.Domain.csproj
- src/Esfa.Vacancy.Register.Infrastructure/Repositories/VacancyRepository.cs
- src/Esfa.Vacancy.Register.Infrastructure/Settings/AppConfigSettingsProvider.cs
I have added few type converters and want to get an early review.
> Vacancy add more fields

- src/Esfa.Vacancy.Register.Api/Global.asax.cs
exceptions are being logged in 2 places - this removes one of those
> removed application error logger as already handled

- src/Esfa.Vacancy.Register.Api/App_Start/AutoMapperConfig.cs
- src/Esfa.Vacancy.Register.Api/Orchestrators/VacancyOrchestrator.cs
- src/Esfa.Vacancy.Register.Domain/Entities/Vacancy.cs
- src/Esfa.Vacancy.Register.Domain/Entities/VacancyStatus.cs
- src/Esfa.Vacancy.Register.Domain/Esfa.Vacancy.Register.Domain.csproj
- src/Esfa.Vacancy.Register.Infrastructure/Repositories/VacancyRepository.cs
- src/Esfa.Vacancy.Register.UnitTests/Api/Orchestrators/VacancyOrchestratorTests/GetVacancyDetailsAsyncTests.cs
- src/Esfa.Vacancy.Register.UnitTests/Esfa.Vacancy.Register.UnitTests.csproj
- src/Esfa.Vacancy.Register.UnitTests/Orchestrators/GetVacancyOrchestratorTests.cs
- src/Esfa.Vacancy.Register.UnitTests/app.config
- src/Esfa.Vacancy.Register.UnitTests/packages.config
… fields and empty address in place of anonymous employer
> Api response returns anonymous employer details where necessary for live vacancies

- src/Esfa.Vacancy.Api.Types/SearchApprenticeshipParameters.cs
- src/Esfa.Vacancy.Register.Application/Queries/SearchApprenticeshipVacancies/SearchApprenticeshipVacanciesRequest.cs
- src/Esfa.Vacancy.Register.Application/Queries/SearchApprenticeshipVacancies/SearchApprenticeshipVacanciesRequestValidator.cs
- src/Esfa.Vacancy.Register.Application/Queries/SearchApprenticeshipVacancies/VacancySearchParametersBuilder.cs
- src/Esfa.Vacancy.Register.Domain/Entities/VacancySearchParameters.cs
- src/Esfa.Vacancy.Register.Infrastructure/Services/ApprenticeshipSearchService.cs
- src/Esfa.Vacancy.Register.UnitTests/Esfa.Vacancy.Register.UnitTests.csproj
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenAVacancySearchParametersBuilder/AndPostedInDays.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenAVacancySearchParametersBuilder/AndPostedInLastNumberOfDays.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenRequestValidator/WhenValidatingPostedInDays.cs
Added parameter to accept number of days to look back in past for newly submitted vacancies. By default the parameter is zero and will be ignored in search.
> RA-1200 Implemented search by posted date

- src/Esfa.Vacancy.Register.Infrastructure/Factories/ElasticClientFactory.cs
- src/Esfa.Vacancy.Register.Infrastructure/Repositories/FrameworkCodeRepository.cs
- src/Esfa.Vacancy.Register.Infrastructure/Repositories/StandardRepository.cs
- src/Esfa.Vacancy.Register.Infrastructure/Repositories/VacancyRepository.cs
- src/Esfa.Vacancy.Register.Infrastructure/Services/ApprenticeshipSearchService.cs
- src/Esfa.Vacancy.Register.Infrastructure/Services/TrainingDetailService.cs
This PR should be reviewed along side
https://github.com/SkillsFundingAgency/das-avmsplus-database/pull/4
> RA-1276 Enable retry and move scripts to DB

- src/Esfa.Vacancy.Api.Types/ApprenticeshipVacancy.cs
- src/Esfa.Vacancy.Api.Types/TraineeshipVacancy.cs
- src/Esfa.Vacancy.Register.Api/Mappings/ApprenticeshipMapper.cs
- src/Esfa.Vacancy.Register.Api/Mappings/TraineeshipMapper.cs
- src/Esfa.Vacancy.Register.Domain/Entities/ApprenticeshipVacancy.cs
- src/Esfa.Vacancy.Register.Domain/Entities/TraineeshipVacancy.cs
Returning TrainingProvider, TrainingProviderUkprn, TrainingProviderSite as part of Apprenticeship and Traineeship vacancies
> RA-1175 - Added Provider and ProviderSite information

- src/Esfa.Vacancy.Register.Api/Global.asax.cs
- src/Esfa.Vacancy.Register.Api/Logging/RequestContext.cs
The logger was requested too early causing all sort of null references. 
The headers were removed too early in the request as well.
> This is to fix bunch of startup errors you get when debugging

- src/Esfa.Vacancy.Api.Types/SearchApprenticeshipParameters.cs
- src/Esfa.Vacancy.Register.Api/Controllers/SearchApprenticeshipVacanciesController.cs
- src/Esfa.Vacancy.Register.Application/Queries/SearchApprenticeshipVacancies/SearchApprenticeshipVacanciesRequest.cs
- src/Esfa.Vacancy.Register.Application/Queries/SearchApprenticeshipVacancies/SearchApprenticeshipVacanciesRequestValidator.cs
- src/Esfa.Vacancy.Register.Application/Queries/SearchApprenticeshipVacancies/VacancySearchParametersMapper.cs
- src/Esfa.Vacancy.Register.Domain/Entities/VacancySearchParameters.cs
- src/Esfa.Vacancy.Register.Domain/Validation/ErrorCodes.cs
- src/Esfa.Vacancy.Register.Domain/Validation/ErrorMessages.cs
- src/Esfa.Vacancy.Register.Infrastructure/Services/ApprenticeshipSearchService.cs
- src/Esfa.Vacancy.Register.UnitTests/Esfa.Vacancy.Register.UnitTests.csproj
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Api/Mappings/GivenASearchApprenticeshipParametersMapper/WhenMappingDistanceInMiles.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Api/Mappings/GivenASearchApprenticeshipParametersMapper/WhenMappingLatitude.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Api/Mappings/GivenASearchApprenticeshipParametersMapper/WhenMappingLongitude.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenASearchApprenticeshipVacanciesRequestValidator/GivenSearchApprenticeshipVacanciesRequestValidatorBase.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenASearchApprenticeshipVacanciesRequestValidator/WhenValidatingDistanceInMiles.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenASearchApprenticeshipVacanciesRequestValidator/WhenValidatingGeoSearchFields.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenASearchApprenticeshipVacanciesRequestValidator/WhenValidatingLatitude.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenASearchApprenticeshipVacanciesRequestValidator/WhenValidatingLocationFields.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenASearchApprenticeshipVacanciesRequestValidator/WhenValidatingLongitude.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenAVacancySearchParametersMapper/AndLocationFields.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Application/GivenAVacancySearchParametersMapper/AndNationwideOnly.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Domain/GivenAVacancySearchParameters/WhenCallingHasGeoSearchFields.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Domain/GivenAVacancySearchParameters/WhenCallingHasLocationFields.cs
- src/Esfa.Vacancy.Register.UnitTests/SearchApprenticeship/Domain/GivenAVacancySearchParameters/WhenCallingToString.cs
I've also added the error codes to xml doc for swagger.
> RA-1277 search by geopoint

- src/Esfa.Vacancy.Register.Api/Controllers/SearchApprenticeshipVacanciesController.cs
**NOTE**: i've removed the geopoint related error codes from the help text (temporarily)
> RA-1245 added help text for nationwide search

- src/Esfa.Vacancy.Api.Types/TraineeshipVacancy.cs
- src/Esfa.Vacancy.Register.Api/Mappings/TraineeshipMapper.cs
- src/Esfa.Vacancy.Register.UnitTests/Esfa.Vacancy.Register.UnitTests.csproj
- src/Esfa.Vacancy.Register.UnitTests/packages.config
- Added NUnit3TestAdapter for live testing
> RA-1353 Renamed TrainingProvider to TrainingProviderName

- src/Esfa.Vacancy.Api.Types/ApprenticeshipSummary.cs
- src/Esfa.Vacancy.Api.Types/ApprenticeshipVacancy.cs
- src/Esfa.Vacancy.Api.Types/TraineeshipVacancy.cs
- src/Esfa.Vacancy.Register.Api/Mappings/ApprenticeshipMapper.cs
- src/Esfa.Vacancy.Register.Api/Mappings/ApprenticeshipSummaryMapper.cs
- src/Esfa.Vacancy.Register.Api/Mappings/TraineeshipMapper.cs
- src/Esfa.Vacancy.Register.Domain/Entities/ApprenticeshipSummary.cs
- src/Esfa.Vacancy.Register.Domain/Entities/ApprenticeshipVacancy.cs
- src/Esfa.Vacancy.Register.Domain/Entities/TraineeshipVacancy.cs
Get Apprenticeship
Get Traineeship
Search Apprenticeship
> RA-1331 add disability confidence in following api responses..

- src/Esfa.Vacancy.Register.Api/Controllers/GetApprenticeshipVacancyController.cs
This has case insensitivity which we do not need and might want to remove.
We need to get master stable so we can make this change after.
> RA-1425 added constraint to get route to filter out search.

- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/Extensions.cs
- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/LongDescriptionValidator.cs
- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/ShortDescriptionValidator.cs
- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/TitleValidator.cs
- src/Esfa.Vacancy.Manage.Api/Controllers/CreateApprenticeshipController.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingWithMatchesAllowedFreeTextCharacters.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingWithMatchesAllowedHtmlFreeTextCharacters.cs
Including property names in error messages.
Added error codes to API summary comments
> RA-1388 title and description validation

- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/Extensions.cs
- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/LongDescriptionValidator.cs
- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/ShortDescriptionValidator.cs
- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/TitleValidator.cs
- src/Esfa.Vacancy.Domain/Validation/ErrorMessages.cs
- src/Esfa.Vacancy.Manage.Api/Controllers/CreateApprenticeshipController.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingLongDescription.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingShortDescription.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingTitle.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingWithMatchesAllowedFreeTextCharacters.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingWithMatchesAllowedHtmlFreeTextCharacters.cs
- Added custom error messages where appropriate
- Updated API documentation. Verified by Darryl.
> RA-1388 adding custom error messages

- src/Esfa.Vacancy.Azure.Resources/APIM/Import-APIMSwaggerApiDefinition.ps1
Change SwaggerSpecificationName to SwaggerSpecificationUrl
> Fix incorrect Parameter name in documentation

- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/Extensions.cs
- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/LocationValidator.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/AndLocationTypeIsNotOther/WhenValidatingLocation.cs
- src/Esfa.Vacancy.UnitTests/Esfa.Vacancy.UnitTests.csproj
Chris found better way of handling Dependent validations, which seems more appropriate. We should use this pattern going forward. 
Changed regex to be lenient on empty strings.
> RA-1530 Refactored When condition to be more accurate in Location

- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/CreateApprenticeshipParametersMapper.cs
- src/Esfa.Vacancy.Domain/Entities/CreateApprenticeshipParameters.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipParametersMapper/WhenMappingFromARequest.cs
Fixes some properties that did not map to param names in the stored proc.
> RA-1547 fixed fields mapping to the stored proc.

- src/Esfa.Vacancy.Azure.Resources/API App/parameters.json
- src/Esfa.Vacancy.Azure.Resources/API App/template.json
Updated template and settings to use sandbox.
> Updated template and parameters

- src/Esfa.Vacancy.Azure.Resources/Manage API App/parameters.json
- src/Esfa.Vacancy.Azure.Resources/Manage API App/template.json
> Updating manage api template

- src/Esfa.Vacancy.Azure.Resources/Manage API App/parameters.json
- src/Esfa.Vacancy.Azure.Resources/Manage API App/template.json
New Template cacheSettings for manage
> RA-1420 Updated template

- src/Esfa.Vacancy.Manage.Api/Controllers/CreateApprenticeshipController.cs
- src/Esfa.Vacancy.Manage.Api/Views/Home/Api.cshtml
- src/Esfa.Vacancy.Manage.Api/Views/Shared/_Header.cshtml
- src/Esfa.Vacancy.Manage.Api/Views/Shared/_Layout.cshtml
Initial draft of the documentation for APIM.
> RA-1599 Updated swagger items for APIM

- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/ContactDetailsValidator.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingContactEmail.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingContactName.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingContactNumber.cs
Modified Contact details to only allow null as valid empty values
> RA-1601 - Modified Contact details to only allow null as valid empty values

- src/Esfa.Vacancy.Azure.Resources/deployments/web-app-resources.json
- src/Esfa.Vacancy.Azure.Resources/parameters.json
- src/Esfa.Vacancy.Azure.Resources/template.json
- src/Esfa.Vacancy.Manage.Api/App_Start/SwaggerConfig.cs
- src/Esfa.Vacancy.Manage.Api/Web.config
> RA-1850 Added new setting to allow generating a unique title 

- src/Esfa.Vacancy.Azure.Resources/deployments/web-app-resources.json
manage and sandbox Web Apps now has InstanceName in Application Settings - used for Swagger definitions
> Added InstanceName to App Settings

- src/Esfa.Vacancy.Azure.Resources/deployments/web-app-resources.json
UseSandboxServices App Setting now correctly set. As this will always be yes the value has been hardcoded
> Sandbox now sets UseSandboxServices to yes

- src/Esfa.Vacancy.Azure.Resources/APIM/Import-APIMSwaggerApiDefinition.ps1
Creation of API (if it did not exist in the APIM) did not work, fixed incorrect if statement and refactored
> Fixed API creation

- src/Esfa.Vacancy.Azure.Resources/deployments/web-app-resources.json
Updated ARM template so that it sets InstanceName correctly on the Live Vacancies API
> InstanceName on Web App Vacancy

- src/Esfa.Vacancy.Azure.Resources/deployments/web-app-resources.json
- src/Esfa.Vacancy.Azure.Resources/template.json
Settings as per RA-1879. As you can see, InstanceName is already there.
> DASD-2966 - Added setting as requested

- src/Esfa.Vacancy.Register.Api/Esfa.Vacancy.Register.Api.csproj
- src/Esfa.Vacancy.Register.Api/packages.config
- src/Esfa.Vacancy.UnitTests/Esfa.Vacancy.UnitTests.csproj
- src/Esfa.Vacancy.UnitTests/packages.config
Updated SFA.DAS.Recruit.Vacancies.Client to latest version for the Mongo Driver update and removed the legacy mongo driver
> RA 2027 Mongo Driver update

- src/Esfa.Vacancy.Azure.Resources/APIM/Import-APIMSwaggerApiDefinition.ps1
- src/Esfa.Vacancy.Manage.Api/Controllers/CreateApprenticeshipController.cs
- src/Esfa.Vacancy.Register.Api/Controllers/GetApprenticeshipVacancyController.cs
- src/Esfa.Vacancy.Register.Api/Controllers/GetTraineeshipVacancyController.cs
- src/Esfa.Vacancy.Register.Api/Controllers/SearchApprenticeshipVacanciesController.cs
> Operation Id fix

- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/ApplicationClosingDateValidator.cs
- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/Validators/ExpectedStartDateValidator.cs
- src/Esfa.Vacancy.Domain/Validation/ErrorMessages.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingApplicationClosingDate.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipRequestValidator/WhenValidatingExpectedStartDate.cs
Updated the error message to include reference to a possible incorrect format which could lead to a default date when binding to the input DTO.
> RA 1526 Modified the date error message

- src/Esfa.Vacancy.Api.Types/ApprenticeshipSummary.cs
- src/Esfa.Vacancy.Api.Types/SearchApprenticeshipParameters.cs
- src/Esfa.Vacancy.Application/Queries/SearchApprenticeshipVacancies/SearchApprenticeshipVacanciesRequest.cs
- src/Esfa.Vacancy.Application/Queries/SearchApprenticeshipVacancies/SearchApprenticeshipVacanciesRequestValidator.cs
- src/Esfa.Vacancy.Application/Queries/SearchApprenticeshipVacancies/VacancySearchParametersMapper.cs
- src/Esfa.Vacancy.Domain/Entities/ApprenticeshipSummary.cs
- src/Esfa.Vacancy.Domain/Entities/VacancySearchParameters.cs
- src/Esfa.Vacancy.Domain/Validation/ErrorCodes.cs
- src/Esfa.Vacancy.Domain/Validation/ErrorMessages.cs
- src/Esfa.Vacancy.Infrastructure/Esfa.Vacancy.Infrastructure.csproj
- src/Esfa.Vacancy.Infrastructure/Services/ApprenticeshipSearchService.cs
- src/Esfa.Vacancy.Infrastructure/packages.config
- src/Esfa.Vacancy.Register.Api/App_Start/AutoMapperConfig.cs
- src/Esfa.Vacancy.Register.Api/Controllers/SearchApprenticeshipVacanciesController.cs
- src/Esfa.Vacancy.Register.Api/Mappings/ApprenticeshipSummaryMapper.cs
- src/Esfa.Vacancy.UnitTests/Esfa.Vacancy.UnitTests.csproj
- src/Esfa.Vacancy.UnitTests/SearchApprenticeship/Api/Mappings/GivenASearchApprenticeshipParametersMapper/WhenMappingTrainingProviderUkprn.cs
- src/Esfa.Vacancy.UnitTests/SearchApprenticeship/Api/Mappings/GivenASearchApprenticeshipParametersMapper/WhenMappingUkprn.cs
- src/Esfa.Vacancy.UnitTests/SearchApprenticeship/Api/Mappings/GivenASearchResponseMapper/WhenMappingApprenticeshipSummary.cs
- src/Esfa.Vacancy.UnitTests/SearchApprenticeship/Application/GivenASearchApprenticeshipVacanciesRequestValidator/WhenValidatingProviderUkprn.cs
- src/Esfa.Vacancy.UnitTests/SearchApprenticeship/Application/GivenAVacancySearchParametersMapper/AndProviderUkprn.cs
- src/Esfa.Vacancy.UnitTests/SearchApprenticeship/Domain/GivenAVacancySearchParameters/WhenCallingToString.cs
- src/Esfa.Vacancy.UnitTests/SearchApprenticeship/Infrastructure/GivenAnApprenticeshipSearchService/WhenSearching.cs
- src/Esfa.Vacancy.UnitTests/packages.config
- Added Training Provider's UKPRN as a search parameter
- Added Training Provider's UKPRN to the returned vacancy
Searching just by UKPRN is a valid search
> ER-1013 - Search by provider UKPRN

- src/Esfa.Vacancy.Register.Api/Esfa.Vacancy.Register.Api.csproj
- src/Esfa.Vacancy.Register.Api/Mappings/RecruitApprenticeshipMapper.cs
- src/Esfa.Vacancy.Register.Api/packages.config
- src/Esfa.Vacancy.UnitTests/Esfa.Vacancy.UnitTests.csproj
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRecruitApprenticeshipMapper/RecruitApprenticeshipMapperBase.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRecruitApprenticeshipMapper/WhenMappingEmployerInformation.cs
- src/Esfa.Vacancy.UnitTests/app.config
- src/Esfa.Vacancy.UnitTests/packages.config
Handling v2 anonymous vacancies
Upgraded SFA.DAS.Recruit.Vacancies.Client to 1.0.172
> ER-1020 v2 anonymous

- src/Esfa.Vacancy.Register.Api/Esfa.Vacancy.Register.Api.csproj
- src/Esfa.Vacancy.Register.Api/Mappings/RecruitApprenticeshipMapper.cs
- src/Esfa.Vacancy.Register.Api/packages.config
- src/Esfa.Vacancy.UnitTests/Esfa.Vacancy.UnitTests.csproj
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRecruitApprenticeshipMapper/RecruitApprenticeshipMapperBase.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRecruitApprenticeshipMapper/WhenMappingEmployerInformation.cs
- src/Esfa.Vacancy.UnitTests/app.config
- src/Esfa.Vacancy.UnitTests/packages.config
Merging release branch into master post release.
> ER-1020 - v2 anonymous employers

- src/Esfa.Vacancy.Api.Types/EducationLevel.cs
- src/Esfa.Vacancy.Application/Commands/CreateApprenticeship/CreateApprenticeshipParametersMapper.cs
- src/Esfa.Vacancy.Domain/Entities/ApprenticeshipType.cs
- src/Esfa.Vacancy.Infrastructure/Services/ApprenticeshipSearchService.cs
- src/Esfa.Vacancy.Register.Api/Esfa.Vacancy.Register.Api.csproj
- src/Esfa.Vacancy.Register.Api/Extensions/EducationLevelHelper.cs
- src/Esfa.Vacancy.Register.Api/Mappings/ApprenticeshipMapper.cs
- src/Esfa.Vacancy.UnitTests/CreateApprenticeship/Application/GivenACreateApprenticeshipParametersMapper/WhenMappingApprenticeshipType.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingEmployerInformation.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingEmployersEmployersApplicationInstructions.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingEmployersRecruitmentWebsite.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingIsNationwide.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipEducationLevel.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipTrainingDetails.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipWageUnit.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipWithAmbiguousWage.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipWithApprenticeshipMinimumWageType.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipWithCustomRangeWageType.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipWithCustomWageType.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipWithLegacyTextWageType.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipWithLegacyWeeklyWageType.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingLiveApprenticeshipWithNationalMinimumWageType.cs
- src/Esfa.Vacancy.UnitTests/GetApprenticeshipVacancy/Api/Mappings/GivenRaaApprenticeshipMapper/WhenMappingVacancyUrl.cs
- src/Esfa.Vacancy.UnitTests/SearchApprenticeship/Infrastructure/GivenAnApprenticeshipSearchService/WhenSearching.cs
* ER-1235 Remove Foundation and Masters apprenticeship levels
* Rename EducationLevelExtensions to EducationLevelHelper
> ER-1235 Remove two apprenticeship levels + semver: minor (#226)
